# Generated by Django 2.1.7 on 2019-02-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cartao',
            field=models.IntegerField(max_length=16),
        ),
    ]
